/**
 * UnsplashImage — Automatic, self-fetching image component for WanderAI
 *
 * Accepts a `query` string that is auto-generated by buildDestinationQuery(),
 * buildEventQuery(), or buildMarketplaceQuery(). Searches Unsplash API and
 * shows the most relevant photo. 24h localStorage cache minimizes API calls.
 *
 * Always renders immediately using `staticSrc` (the pre-stored Unsplash URL)
 * and silently upgrades to the API-fetched image once available.
 */
import { useState, useEffect, useRef } from 'react';
import { fetchUnsplashImage } from '../services/unsplashService';

interface UnsplashImageProps {
  /** Auto-generated search query — produced by buildDestinationQuery() etc. */
  query: string;
  /** Immediate fallback shown while API loads (from mockData / DB) */
  staticSrc: string;
  alt: string;
  className?: string;
  onError?: (e: React.SyntheticEvent<HTMLImageElement>) => void;
}

export function UnsplashImage({ query, staticSrc, alt, className, onError }: UnsplashImageProps) {
  const [src, setSrc] = useState<string>(staticSrc);
  const prevQuery = useRef<string>('');

  useEffect(() => {
    // Avoid re-fetching for the same query
    if (query === prevQuery.current) return;
    prevQuery.current = query;

    let cancelled = false;
    fetchUnsplashImage(query).then((entry) => {
      if (!cancelled && entry?.url) {
        setSrc(entry.url);
      }
    });

    return () => { cancelled = true; };
  }, [query]);

  // Update static src if it changes (e.g. navigation)
  useEffect(() => {
    if (!src || src === staticSrc) return;
    // keep API result, don't downgrade back to static
  }, [staticSrc]);

  return (
    <img
      src={src}
      alt={alt}
      className={className}
      onError={(e) => {
        if (src !== staticSrc) setSrc(staticSrc);
        onError?.(e);
      }}
    />
  );
}
